<?php

// Seeder generated from c:/laragon/www/#Project2026/indracocoffee-v2-laravel-7/db/db-indracocoffee-v2-laravel-10.sql for master_variant

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterVariantSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('master_variant')->truncate();

        DB::unprepared(<<<'SQL'
INSERT INTO `master_variant` VALUES (1, 2, 'Signature Blend', 'Signature-Blend', '100% Arabica. Pure 100% Arabica coffee beans originating from various regions in Indonesia, and roasted with the Full City Roast mode. Relish in unmatched acidity along with hints of warm spices, tropical fruits and chocolaty caramel nuances.', 'Tropical Fruity - Warm Spices - Choco Caramel Nuances', 3.0, 3.0, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/Signature-Blend_map_1774494550.png', 0.45, 'images/uploads/variant/Signature-Blend_icon_1774424500.png', '#797a7d', '#ffffff', 'active', NULL, '2026-03-17 16:13:20', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (2, 2, 'Espresso Blend', 'Espresso-Blend', '70% Arabica - 30% Robusta. A 70/30 blend of Arabica and Robusta beans originating from the vast regions of Indonesia and roasted with the Full City Roast mode. Experience the dark chocolate hints alongside caramel and romantic florals of this one of a kind blend with medium acidity and heavy body.', 'Dark Chocolate - Caramel - Romantic Florals', 3.0, 4.0, 'Full City Roast', '70% Arabica & 30% Robusta Coffee', 'images/uploads/variant/Espresso-Blend_map_1774494537.png', 0.45, 'images/uploads/variant/Espresso-Blend_icon_1774424534.png', '#24a8a3', '#ffffff', 'active', NULL, '2026-03-17 16:13:20', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (3, 2, 'Equilibre Blend', 'Equilibre-Blend', '50% Arabica - 50% Robusta. A 50/50 blend of Arabica and Robusta beans made with coffee grown and farmed in Indonesia and roasted with the City+ Roast mode. With a lower acidity compared to our Signature and Espresso blends, Equilibre is a balanced blend which possesses good body alongside sweet fruity and floral aftertastes with nutty and warm spice nuances.', 'Sweet Fruity Floral Aftertaste - Nutty Warm Spice Nuances', 2.0, 3.0, 'City+ Roast', '50% Arabica & 50% Robusta Coffee', 'images/uploads/variant/Equilibre-Blend_map_1774494524.png', 0.45, 'images/uploads/variant/Equilibre-Blend_icon_1774424556.png', '#7b7727', '#ffffff', 'active', NULL, '2026-03-17 16:13:20', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (4, 2, 'Lumiere Blend', 'Lumiere-Blend', '30% Arabica - 70% Robusta. A 30/70 blend of Arabica and Robusta beans originating from the different regions of Indonesia and roasted with the City+ Roast mode. Taste the complementary sweet chocolaty hints, warm spices and slight earthiness amongst the caramel chocolaty undertones, with lower acidity and strong body.', 'Sweet Chocolaty & Warm Spices - Slight Earthy - Caramel Chocolaty Undertones', 1.0, 4.5, 'City+ Roast', '30% Arabica Coffee & 70% Robusta', 'images/uploads/variant/Lumiere-Blend_map_1774494510.png', 0.45, 'images/uploads/variant/Lumiere-Blend_icon_1774424575.png', '#837bfa', '#ffffff', 'active', NULL, '2026-03-17 16:13:20', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (5, 2, 'Exotic Blend', 'Exotic-Blend', '20% Arabica - 80% Robusta. An 20/80 blend of Arabica and Robusta roasted with the City+ Roast mode and consisting of only Indonesian beans. Its lowest acidity amongst our Gourmet Collection and high bitterness characterise this blend, with sweet chocolaty aftertastes and woody, nuttiness in its undertones.', 'Sweet Chocolaty Aftertaste - Woody - Nutty - Chocolaty Undertones', 1.0, 4.0, 'City+ Roast', '20% Arabica Coffee & 80% Robusta', 'images/uploads/variant/Exotic-Blend_map_1774494497.png', 0.45, 'images/uploads/variant/Exotic-Blend_icon_1774424597.png', '#ac1239', '#ffffff', 'active', NULL, '2026-03-17 16:13:20', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (6, 2, 'Ombre Blend', 'Ombre-Blend', '100% Robusta. A robusta blend consisting of only Indonesian beans roasted to Full City roast. Characterised with no acidity and a strong body, rich choco caramel aftertastes and woody nuttiness in its undertones complete this blend.', 'Rich Choco Caramel - Nutty - Spicy - Sweet Chocolaty', 0.0, 5.0, 'Full City Roast', '100% Robusta Coffee', 'images/uploads/variant/Ombre-Blend_map_1774494485.png', 0.45, 'images/uploads/variant/Ombre-Blend_icon_1774424624.png', '#483749', '#ffffff', 'active', 0, '2026-03-17 16:13:20', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (7, 2, 'Décaféiné Blend', 'Decafeine-Blend', 'Teeming with exceptional fragrances alongside hints of caramel and spices, this dark roast coffee is smooth and medium-bodied with delicate acidity, all wrapped in a decaffeinated package.', 'Boldly Roasted - Notes of Caramel & Spices - Delicate Acidity', 0.5, 3.0, 'Dark Roast', '100% Arabica Coffee', 'images/uploads/variant/Decafeine-Blend_map_1774494473.png', 0.45, 'images/uploads/variant/Decafeine-Blend_icon_1774424643.png', '#345461', '#ffffff', 'active', 0, '2026-03-17 16:14:18', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (8, 1, 'Аceh Gayo', 'Асеh-Gayo', 'Aceh Gayo coffee is often used in most coffee shops commonly for cafe latte. It has light earthy notes with a mild body and bittersweet spicy chocolate taste. Soft in acidity, this coffee reveals some elegant caramel-fruity flavours, marrying a perfect combination of spicy and sweet. Its unique taste will make you crave for more.', 'Spicy - Caramel & Chocolaty - Fruity - Slightly Earthy Note', 3.0, 2.5, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/Асен-Gayo_map_1774514521.png', 0.45, 'images/uploads/variant/Асен-Gayo_icon_1774403746.png', '#00a5cd', '#ffffff', 'active', NULL, '2026-03-17 16:14:48', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (9, 1, 'Sumatra Mandheling', 'Sumatra-Mandheling', 'These Arabica coffee beans are not only rare and rich in history but also one of the highly recognised by gourmet coffee producers in the world. The syrupy, full body of Sumatra Mandheling, combined with its muted acidity, makes an elegant, smooth cup of coffee. A blend of sweet and spicy, exuding an exotic flavour.', 'Floral & Fruity - Sweet & Spicy - Slightly Earthy Undertones', 4.0, 3.0, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/Sumatra-Mandheling_map_1774514578.png', 0.45, 'images/uploads/variant/Sumatra-Mandheling_icon_1773888433.png', '#d2441e', '#ffffff', 'active', NULL, '2026-03-17 16:14:48', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (10, 1, 'Lampung', 'Lampung', 'Well-sought after by the worlds coffee industry, this Robusta coffee gives off an immense strong-bodied bitter taste with the essence of chocolate, slightly earthy aroma and tobacco undertones. The absence of acidity is Lampungs trademark.', 'Chocolaty - Slightly Earthy - Tobacco Notes', 0.0, 5.0, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/Lampung_map_1774514589.png', 0.45, 'images/uploads/variant/Lampung_icon_1773888420.png', '#e54078', '#ffffff', 'active', NULL, '2026-03-17 16:14:48', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (11, 1, 'Manglayang', 'Manglayang', 'Famous for its traditional coffee cultivation that retains its original character and distinctive flavours, our Manglayang Arabica coffee provides a smooth, medium body. The gentle plum acidity flavour it exudes, complements its sweet maple syrup notes, leaving a fruity lingering mouthfeel.', 'Sweet Maple Syrup - Fruity - Acidic Plum', 2.5, 3.0, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/Manglayang_map_1774514602.png', 0.45, 'images/uploads/variant/Manglayang_icon_1773888408.png', '#ff595b', '#ffffff', 'active', NULL, '2026-03-17 16:14:48', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (12, 1, 'West Java', 'West-Java', 'West Java coffees sour flavour is not too dominant yet not too earthy. They have a berry-like, wine taste with a sweet honey aroma that taste great on their own or paired well with dark chocolate desserts that accentuates its flavour. To bring out its earthiness, enjoy it with a hearty brunch made with cheese, mushrooms or bacon.', 'Wine Taste - Berry Like - Sweet Hone', 0.0, 4.0, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/West-Java_map_1774514613.png', 0.45, 'images/uploads/variant/West-Java_icon_1773888398.png', '#046240', '#ffffff', 'active', NULL, '2026-03-17 16:14:48', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (13, 1, 'Java', 'Java', 'Supresso Java Robusta coffee beans are thoroughly wet-processed, kicking off the acidity, drops the body and reduces the earthiness of the cup to a unique sweetness. Its strong malty taste with hints of tobacco notes will give a perfect combination when added with cocoa - great for brewing your delicious mocha.', 'Sweetness - Strong Malty - Tobacco Notes', 0.0, 3.0, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/Java_map_1774514624.png', 0.45, 'images/uploads/variant/Java_icon_1773888332.png', '#80bc04', '#ffffff', 'active', NULL, '2026-03-17 16:14:48', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (14, 1, 'Bali Kintamani', 'Bali-Kintamani', 'Grown in the highlands of Kintamani, this coffee has unique characteristics derived from wet processing method, making them slightly sweeter. The mild body of the coffee exudes a clean light and refreshing taste exhibiting a citrusy, fruity finish. It is a must-try for those who do not like the bitter taste.', 'Good Balance - Herbal & Nutty - Lively Acidity - Sweet Citrus Notes', 3.0, 2.5, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/Bali-Kintamani_map_1774514637.png', 0.45, 'images/uploads/variant/Bali-Kintamani_icon_1773888324.png', '#e90b2a', '#ffffff', 'active', NULL, '2026-03-17 16:14:48', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (15, 1, 'Flores Bajawa', 'Flores-Bajawa', 'Aceh Gayo coffee is often used in most coffee shops commonly for cafe latte. It has light earthy notes with a mild body and bittersweet spicy chocolate taste. Soft in acidity, this coffee reveals some elegant caramel-fruity flavours, marrying a perfect combination of spicy and sweet. Its unique taste will make you crave for more.', 'Chocolate Fudges - Floral Nectareous Sweetness - Vanilla Hints - Caramel Undertones', 2.0, 4.0, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/Flores-Bajawa_map_1774518242.png', 0.45, 'images/uploads/variant/Flores-Bajawa_icon_1773888310.png', '#d939b3', '#ffffff', 'active', NULL, '2026-03-17 16:14:48', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (16, 1, 'Toraja Kalosi', 'Toraja-Kalosi', 'Our Supresso Toraja Kalosi is highly valued among Japans coffee drinkers because of its quality traditional processing, offering multiple layers of flavours that reveal something upon each sip. The heavy-bodied coffee is low in acidity, and its delicate aroma denotes warm spices with a sweet and smooth aftertaste.', 'Warm Spices - Sweet & Smooth Aftertastes', 2.0, 3.5, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/Toraja-Kalosi_map_1774518232.png', 0.50, 'images/uploads/variant/Toraja-Kalosi_icon_1773888029.png', '#facd00', '#000000', 'active', NULL, '2026-03-17 16:14:48', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (17, 2, 'Arabica Gold', 'arabica-gold', '', '', 0.0, 0.0, '', '', '', 0.45, '', '#0c86ad', '#ffffff', 'inactive', NULL, '2026-03-25 10:12:30', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (18, 2, 'Robusta', 'robusta', '', '', 0.0, 0.0, '', '', '', 0.45, '', '#0c86ad', '#ffffff', 'inactive', NULL, '2026-03-25 10:13:19', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (19, 2, 'Peaberry Robusta', 'peaberry-robusta', '', '', 0.0, 0.0, '', '', '', 0.45, '', '#0c86ad', '#ffffff', 'inactive', NULL, '2026-03-25 10:13:38', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (20, 2, 'Sunset Blend', 'sunset-blend', '', '', 0.0, 0.0, '', '', '', 0.45, '', '#0c86ad', '#ffffff', 'inactive', NULL, '2026-03-25 10:13:55', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (21, 2, 'Luwak Arabica', 'luwak-arabica', '', '', 0.0, 0.0, '', '', 'images/uploads/variant/luwak-arabica_map_1774489282.png', 0.45, '', '#0c86ad', '#ffffff', 'inactive', NULL, '2026-03-25 10:14:05', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (22, 1, 'Arabica Gold', 'arabica-gold', '', '', 0.0, 0.0, '', '', '', 0.45, '', '#0c86ad', '#ffffff', 'inactive', NULL, '2026-03-25 10:14:18', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (23, 1, 'Robusta', 'robusta', '', '', 0.0, 0.0, '', '', '', 0.45, '', '#0c86ad', '#ffffff', 'inactive', NULL, '2026-03-25 10:14:56', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (24, 1, 'Peaberry Robusta', 'peaberry-robusta', '', '', 0.0, 0.0, '', '', '', 0.45, '', '#0c86ad', '#ffffff', 'inactive', NULL, '2026-03-25 10:15:04', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (25, 1, 'Sunset Blend', 'sunset-blend', '', '', 0.0, 0.0, '', '', '', 0.45, '', '#0c86ad', '#ffffff', 'inactive', NULL, '2026-03-25 10:15:15', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (26, 1, 'Luwak Arabica', 'luwak-arabica', '', '', 0.0, 0.0, '', '', '', 0.45, '', '#0c86ad', '#ffffff', 'inactive', NULL, '2026-03-25 10:15:33', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (27, 7, 'Sumatra Peaberry', 'sumatra-peaberry', 'Peaberry is known to be significantly sweeter than other beans because of its exclusive access to the fruit. With delicate fruity fragrance, as well as subtle nutty and herbal character, the medium acidity enveloped in sweetness carries through into the long finish.', 'Fresh Herbal - Fruity Cereal - Sweet & Long Aftertastes', 3.0, 3.0, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/sumatra-peaberry_map_1774494768.png', 0.45, 'images/uploads/variant/sumatra-peaberry_icon_1774413330.png', '#0c86ad', '#ffffff', 'active', 2, '2026-03-25 11:35:30', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (28, 7, 'Luwak Prestige', 'luwak-prestige', 'Characterised by its velvety and sweet chocolaty-caramel taste profile, Luwak is a rare and exotic coffee that leaves every coffee lover intrigued and typically found on bucket lists around the world. A perfect cup for you if you like your coffee smooth with a clean aftertaste.', 'Chocolaty Caramel - Velvety Sweetness - Clean Aftertastes', 1.5, 3.0, 'Full City Roast', '100% Civet Arabica Coffee', 'images/uploads/variant/luwak-prestige_map_1774507507.png', 0.45, 'images/uploads/variant/luwak-prestige_icon_1774413386.webp', '#85754e', '#ffffff', 'active', 1, '2026-03-25 11:36:26', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (29, 7, 'Java Arabicа Organic', 'java-arabic-organic', 'One of the best farm-to-cup Indonesian coffee comes from Java. These USDA organic approved beans are grown in high altitude without the use of pesticides, herbicides, or other chemicals. With mild acidity and heavy-body, its flavour is elegantly sweet with a subtle earthiness that lingers on.', 'Delicate Sweetness - Slightly Earthy - Woody & Herbal - Long Aftertastes', 1.5, 3.0, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/java-arabic-organic_map_1774494413.png', 0.45, 'images/uploads/variant/java-arabic-organic_icon_1774413434.webp', '#7f0099', '#ffffff', 'active', 4, '2026-03-25 11:37:14', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (30, 7, 'Sumatra Mandheling Rainforest', 'sumatra-mandheling-rainforest', 'Considered by many to be the best coffee beans that Sumatra produces, our Rainforest Alliance Certified Sumatra Mandheling Rainforest coffee is packed with sweet floral and fruity flavours, and a spicy aroma that finishes off with a slightly earthy undertone. You can try pairing our Sumatran coffee with sweet and creamy desserts.', 'Floral & Fruity - Sweet - Spicy - Slightly Earthy Undertones', 4.0, 3.0, 'Full City Roast', '100% Arabica Coffee', 'images/uploads/variant/sumatra-mandheling-rainforest_map_1774494397.png', 0.45, 'images/uploads/variant/sumatra-mandheling-rainforest_icon_1774413483.webp', '#1c8000', '#ffffff', 'active', 3, '2026-03-25 11:38:03', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (31, 9, 'Kraton', 'kraton', 'New Normal, New Changes.\r\n\r\nSpecification\r\nDimensions :\r\n102mm x 337mm x 220mm\r\nWeight : 2.6kg\r\nWater container capacity : 550ml', '', 0.0, 0.0, '', '', 'images/uploads/variant/kraton_map_1774512355.png', 0.45, 'images/uploads/variant/kraton_icon_1774422025.png', '#ff7a33', '#ffffff', 'active', NULL, '2026-03-25 13:54:21', NULL, NULL, NULL);

INSERT INTO `master_variant` VALUES (32, 11, 'Costa Rica Blend', 'costa-rica-blend', '<p>Costa Rican coffees believed to have some of the best coffee flavour profiles in the south and central America. Our medium-bodied drip coffee has a defining hazelnut and almond taste with hints of red apple tones and subtle acidity. Your savoury, hearty breakfast will be a good pairing with our blend.</p>', '<p>Red Apples - Almonds - Roasted Hazelnut</p>', 3.0, 3.0, 'Full City Roast', '<p>60% Costa Rican Coffee &amp; 40% Arabica Coffee</p>', 'images/variants/1778547186_Costa Rica.png', 0.15, 'images/variants/1778472405_icon_DRIP wb costa 1.png', '#6E3629', '#e8e8e8', 'active', 0, '2026-05-11 10:20:07', 33, 6, 18);

INSERT INTO `master_variant` VALUES (33, 11, 'Brazilia Blend', 'brazilia-blend', '<p>Intense nuttiness, low acidity and hints of berry-like flavour that offers an excellent bittersweet chocolate taste, our Brazilia Blend drip coffee is not only perfect on its own. It is also an excellent base for brewing flavoured coffees and cappuccino.</p>', '<p>Intense Nuttiness - Berry Like - Dark Chocolate</p>', 2.0, 4.0, 'Full City Roast', '<p>60% Brazilian Coffee &amp; 40% Arabica Coffee</p>', 'images/variants/1778547156_Brazil.png', 0.15, 'images/variants/1778472383_icon_DRIP wb brazil 1.png', '#250187', '#d6d6d6', 'active', 0, '2026-05-11 10:20:33', 33, 6, 18);

INSERT INTO `master_variant` VALUES (34, 11, 'Nanyang Coffee', 'nanyang-coffee', '<p>Our Nanyang Coffee is a favourite of the older generation due to its traditional old-school flavour that delights your palate with every sip reminding you of home. It has a rich and robust aroma that exudes a gentle, bittersweet taste, best paired with your morning kaya or peanut butter toast and half-boiled eggs.</p>', '<p>Rich &amp; Strong</p>', 0.0, 0.0, 'Rich & Strong', '<p>100% Pure Coffee</p>', 'images/variants/1778547236_Nanyang (2).png', 0.40, 'images/variants/1778471962_icon_DRIP NANYANG 1.png', '#ECC6A1', '#333333', 'active', 0, '2026-05-11 10:21:40', 33, 6, 18);
SQL
        );

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
